-- METAMAC-1939: Categorizaciones

CREATE sequence SEQ_CATEGORISATIONS;
 	
CREATE sequence SEQ_CATEGORISATION_SEQUENCES;

CREATE TABLE TB_CATEGORISATIONS (
  ID NUMBER(19) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  CATEGORY_FK NUMBER(19) NOT NULL,
  DATASET_VERSION_FK NUMBER(19) NOT NULL,
  VERSIONABLE_RESOURCE_FK NUMBER(19) NOT NULL,
  MAINTAINER_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_CATEGORISATION_SEQUENCES (
  ID NUMBER(19) NOT NULL,
  MAINTAINER_URN VARCHAR2(255 CHAR) NOT NULL,
  ACTUAL_SEQUENCE NUMBER(19) NOT NULL
);



ALTER TABLE TB_CATEGORISATIONS ADD CONSTRAINT PK_TB_CATEGORISATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_CATEGORISATION_SEQUENCES ADD CONSTRAINT PK_TB_CATEGORISATION_SEQUENCES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_CATEGORISATIONS ADD CONSTRAINT FK_TB_CATEGORISATIONS_CATEGO93
	FOREIGN KEY (CATEGORY_FK) REFERENCES TB_EXTERNAL_ITEMS (ID) DEFERRABLE initially IMMEDIATE
;
ALTER TABLE TB_CATEGORISATIONS ADD CONSTRAINT FK_TB_CATEGORISATIONS_DATASE72
	FOREIGN KEY (DATASET_VERSION_FK) REFERENCES TB_DATASETS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE
;
ALTER TABLE TB_CATEGORISATIONS ADD CONSTRAINT FK_TB_CATEGORISATIONS_VERSIO68
	FOREIGN KEY (VERSIONABLE_RESOURCE_FK) REFERENCES TB_STAT_RESOURCES (ID) DEFERRABLE initially IMMEDIATE
;
ALTER TABLE TB_CATEGORISATIONS ADD CONSTRAINT FK_TB_CATEGORISATIONS_MAINTA79
	FOREIGN KEY (MAINTAINER_FK) REFERENCES TB_EXTERNAL_ITEMS (ID) DEFERRABLE initially IMMEDIATE
;

