

ALTER TABLE	TB_QUERIES_VERSIONS modify DATASET_VERSION_FK NUMBER(19) NULL;
alter table	TB_QUERIES_VERSIONS add  DATASET_FK NUMBER(19);

ALTER TABLE TB_QUERIES_VERSIONS ADD CONSTRAINT QUERY_DATASET CHECK ( NOT ( DATASET_FK IS NULL AND DATASET_VERSION_FK IS NULL ) );