-- --------------------------------------------------------------------------------------------------
-- METAMAC-2714 - Permitir la creación de multidataset en la aplicación de gestión
-- --------------------------------------------------------------------------------------------------

-- Sequences
CREATE sequence SEQ_MULTIDATASETS;
CREATE sequence SEQ_MULTIDATASETS_VERSIONS;
CREATE sequence SEQ_MD_CUBES;


-- Tables
CREATE TABLE TB_MULTIDATASETS (
  ID NUMBER(19) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  IDENTIFIABLE_RESOURCE_FK NUMBER(19) NOT NULL
);

CREATE TABLE TB_MULTIDATASETS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  FORMAT_EXTENT_RESOURCES NUMBER(10),
  VERSION NUMBER(19) NOT NULL,
  SIEMAC_RESOURCE_FK NUMBER(19) NOT NULL,
  MULTIDATASET_FK NUMBER(19) NOT NULL
);

CREATE TABLE TB_MD_CUBES (
  ID NUMBER(19) NOT NULL,
  ORDER_IN_MULTIDATASET NUMBER(19) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  STATISTICAL_RESOURCE_FK NUMBER(19) NOT NULL,
  DATASET_FK NUMBER(19),
  QUERY_FK NUMBER(19),
  MULTIDATASET_VERSION_FK NUMBER(19) NOT NULL
);

-- Related resource
ALTER TABLE TB_RELATED_RESOURCES ADD MULTIDATASET_VERSION_FK NUMBER(19);
ALTER TABLE TB_RELATED_RESOURCES ADD MULTIDATASET_FK NUMBER(19);

-- Constrains
ALTER TABLE TB_MULTIDATASETS ADD CONSTRAINT PK_TB_MULTIDATASETS PRIMARY KEY (ID);
ALTER TABLE TB_MULTIDATASETS ADD CONSTRAINT UQ_TB_MULTIDATASETS UNIQUE (ID);

ALTER TABLE TB_MULTIDATASETS_VERSIONS ADD CONSTRAINT PK_TB_MULTIDATASETS_VERSIONS PRIMARY KEY (ID);
ALTER TABLE TB_MULTIDATASETS_VERSIONS ADD CONSTRAINT UQ_TB_MULTIDATASETS_VERSIONS UNIQUE (ID);

ALTER TABLE TB_MD_CUBES ADD CONSTRAINT PK_TB_MD_CUBES PRIMARY KEY (ID);
ALTER TABLE TB_MD_CUBES ADD CONSTRAINT UQ_TB_MD_CUBES UNIQUE (ID);
ALTER TABLE TB_MD_CUBES ADD CONSTRAINT FK_TB_MD_CUBES_STATISTICAL_R70 
    FOREIGN KEY (STATISTICAL_RESOURCE_FK) REFERENCES TB_STAT_RESOURCES (ID) DEFERRABLE initially IMMEDIATE;
ALTER TABLE TB_MD_CUBES ADD CONSTRAINT FK_TB_MD_CUBES_DATASET_FK
    FOREIGN KEY (DATASET_FK) REFERENCES TB_DATASETS (ID) DEFERRABLE initially IMMEDIATE;
ALTER TABLE TB_MD_CUBES ADD CONSTRAINT FK_TB_MD_CUBES_QUERY_FK
    FOREIGN KEY (QUERY_FK) REFERENCES TB_QUERIES (ID) DEFERRABLE initially IMMEDIATE;
ALTER TABLE TB_MD_CUBES ADD CONSTRAINT FK_TB_MD_CUBES_MULTIDATASET_28
    FOREIGN KEY (MULTIDATASET_VERSION_FK) REFERENCES TB_MULTIDATASETS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE;

commit;
