
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index
DROP INDEX IX_TB_STAT_RESOURCES_STAT_RESOURCE_TYPE;


-- Drop many to many relations
    
DROP TABLE TB_SR_VRATIONALE_TYPES CASCADE;

DROP TABLE TB_RR_HAS_PART CASCADE;

DROP TABLE TB_EI_STAT_OPER_INSTANCES CASCADE;

DROP TABLE TB_EI_STATISTICAL_UNIT CASCADE;

DROP TABLE TB_EI_PUB_CONTRIBUTORS CASCADE;

DROP TABLE TB_EI_PUBLISHERS CASCADE;

DROP TABLE TB_EI_MEDIATORS CASCADE;

DROP TABLE TB_EI_LANGUAGES CASCADE;

DROP TABLE TB_EI_CONTRIBUTORS CASCADE;

DROP TABLE TB_DV_TEMP_GRANULARITY CASCADE;

DROP TABLE TB_DV_TEMP_COVERAGE CASCADE;

DROP TABLE TB_DV_MEASURE_COVERAGE CASCADE;

DROP TABLE TB_DV_GEO_GRANULARITY CASCADE;

DROP TABLE TB_DV_GEO_COVERAGE CASCADE;

-- Drop normal entities
    
DROP TABLE TB_TASKS CASCADE;

DROP TABLE TB_CODE_ITEMS CASCADE;

DROP TABLE TB_QUERY_SELECTION_ITEMS CASCADE;

DROP TABLE TB_CHAPTERS CASCADE;

DROP TABLE TB_ELEMENTS_LEVELS CASCADE;

DROP TABLE TB_CUBES CASCADE;

DROP TABLE TB_MD_CUBES CASCADE;

DROP TABLE TB_TEMP_CODES CASCADE;

DROP TABLE TB_DIM_REPR_MAPPING CASCADE;

DROP TABLE TB_DATASOURCES CASCADE;

DROP TABLE TB_CODE_DIMENSIONS CASCADE;

DROP TABLE TB_CATEGORISATION_SEQUENCES CASCADE;

DROP TABLE TB_CATEGORISATIONS CASCADE;

DROP TABLE TB_ATTRIBUTE_VALUES CASCADE;

DROP TABLE TB_TRANSLATIONS CASCADE;

DROP TABLE TB_LOCALISED_STRINGS CASCADE;

DROP TABLE TB_VERSION_RATIONALE_TYPE CASCADE;

DROP TABLE TB_RELATED_RESOURCES CASCADE;

DROP TABLE TB_MULTIDATASETS_VERSIONS CASCADE;

DROP TABLE TB_MULTIDATASETS CASCADE;

DROP TABLE TB_QUERIES_VERSIONS CASCADE;

DROP TABLE TB_QUERIES CASCADE;

DROP TABLE TB_PUBLICATIONS_VERSIONS CASCADE;

DROP TABLE TB_PUBLICATIONS CASCADE;

DROP TABLE TB_DATASETS_VERSIONS CASCADE;

DROP TABLE TB_DATASETS CASCADE;

DROP TABLE TB_LIS_STAT_OFFICIALITY CASCADE;

DROP TABLE TB_STAT_RESOURCES CASCADE;

DROP TABLE TB_EXTERNAL_ITEMS CASCADE;

DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE;


-- Drop pk sequence
    
 	
drop sequence SEQ_I18NSTRS;
 	
drop sequence SEQ_EXTERNAL_ITEMS;
 	
drop sequence SEQ_STAT_RESOURCES;
 	
drop sequence SEQ_STAT_OFFICIALITY;
 	
drop sequence SEQ_DATASETS;
 	
drop sequence SEQ_DATASETS_VERSIONS;
 	
drop sequence SEQ_PUBLICATIONS;
 	
drop sequence SEQ_PUBLICATIONS_VERSIONS;
 	
drop sequence SEQ_QUERIES;
 	
drop sequence SEQ_QUERIES_VERSIONS;
 	
drop sequence SEQ_MULTIDATASETS;
 	
drop sequence SEQ_MULTIDATASETS_VERSIONS;
 	
drop sequence SEQ_RELATED_RESOURCES;
 	
drop sequence SEQ_VERSION_RATIONALE_TYPE;
 	
drop sequence SEQ_L10NSTRS;
 	
drop sequence SEQ_TRANSLATIONS;
 	
drop sequence SEQ_ATTRIBUTE_VALUES;
 	
drop sequence SEQ_CATEGORISATIONS;
 	
drop sequence SEQ_CATEGORISATION_SEQUENCES;
 	
drop sequence SEQ_CODE_DIMENSIONS;
 	
drop sequence SEQ_DATASOURCES;
 	
drop sequence SEQ_DIM_REPR_MAPPING;
 	
drop sequence SEQ_TEMP_CODES;
 	
drop sequence SEQ_MD_CUBES;
 	
drop sequence SEQ_CUBES;
 	
drop sequence SEQ_ELEMENTS_LEVELS;
 	
drop sequence SEQ_CHAPTERS;
 	
drop sequence SEQ_QUERY_SELECTION_ITEMS;
 	
drop sequence SEQ_CODE_ITEMS;
 	
drop sequence SEQ_TASKS;
 	


	