// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.siemac.metamac.statistical.resources.core.io.serviceimpl.validators;

public class CodeHierarchyBuilder extends CodeHierarchyBuilderBase<CodeHierarchyBuilder> {

    public static CodeHierarchyBuilder codeHierarchy() {
        return new CodeHierarchyBuilder();
    }

    public CodeHierarchyBuilder() {
        super(new CodeHierarchy());
    }

    public CodeHierarchy build() {
        return getInstance();
    }
}

class CodeHierarchyBuilderBase<GeneratorT extends CodeHierarchyBuilderBase<GeneratorT>> {

    private CodeHierarchy instance;

    protected CodeHierarchyBuilderBase(CodeHierarchy aInstance) {
        instance = aInstance;
    }

    protected CodeHierarchy getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCode(String aValue) {
        instance.setCode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withParent(CodeHierarchy aValue) {
        instance.setParent(aValue);

        return (GeneratorT) this;
    }

    public ParentCodeHierarchyBuilder withParent() {
        CodeHierarchy obj = new CodeHierarchy();

        withParent(obj);

        return new ParentCodeHierarchyBuilder(obj);
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUrn(String aValue) {
        instance.setUrn(aValue);

        return (GeneratorT) this;
    }

    public class ParentCodeHierarchyBuilder extends CodeHierarchyBuilderBase<ParentCodeHierarchyBuilder> {

        public ParentCodeHierarchyBuilder(CodeHierarchy aInstance) {
            super(aInstance);
        }

        @SuppressWarnings("unchecked")
        public GeneratorT endParent() {
            return (GeneratorT) CodeHierarchyBuilderBase.this;
        }
    }
}
