-- Añadir metadato attributesCoverage

CREATE sequence SEQ_ATTRIBUTE_VALUES;

CREATE TABLE TB_ATTRIBUTE_VALUES (
  ID NUMBER(19) NOT NULL,
  DSD_COMPONENT_ID VARCHAR2(255 CHAR) NOT NULL,
  IDENTIFIER VARCHAR2(255 CHAR) NOT NULL,
  TITLE VARCHAR2(4000 CHAR) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DATASET_VERSION_FK NUMBER(19) NOT NULL
);

ALTER TABLE TB_ATTRIBUTE_VALUES ADD CONSTRAINT PK_TB_ATTRIBUTE_VALUES
	PRIMARY KEY (ID)
;
  
ALTER TABLE TB_ATTRIBUTE_VALUES ADD CONSTRAINT FK_TB_ATTRIBUTE_VALUES_DATAS40
	FOREIGN KEY (DATASET_VERSION_FK) REFERENCES TB_DATASETS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE
;
