

-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    
 	
CREATE sequence SEQ_I18NSTRS;
 	
CREATE sequence SEQ_EXTERNAL_ITEMS;
 	
CREATE sequence SEQ_STATISTICAL_RESOURCES;
 	
CREATE sequence SEQ_L10NSTRS;
 	
CREATE sequence SEQ_DATASETS;
 	
CREATE sequence SEQ_DATASETS_VERSIONS;
 	
CREATE sequence SEQ_DATASOURCES;
 	
CREATE sequence SEQ_PUBLICATIONS;
 	
CREATE sequence SEQ_PUBLICATIONS_VERSIONS;
 	
CREATE sequence SEQ_QUERIES;
 	


-- Create normal entities
    
CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(255) NOT NULL,
  URI VARCHAR2(4000) NOT NULL,
  URN VARCHAR2(4000) NOT NULL,
  MANAGEMENT_APP_URL VARCHAR2(4000),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19),
  TYPE VARCHAR2(255) NOT NULL
);


CREATE TABLE TB_STATISTICAL_RESOURCES (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  OPERATION_FK NUMBER(19),
  STATISTICAL_RESOURCE_TYPE VARCHAR2(255) NOT NULL,
  CODE VARCHAR2(255),
  URI VARCHAR2(255),
  URN VARCHAR2(255),
  TITLE_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  VERSION_LOGIC VARCHAR2(255),
  VERSION_DATE_TZ VARCHAR2(50),
  VERSION_DATE TIMESTAMP ,
  NEXT_VERSION_DATE_TZ VARCHAR2(50),
  NEXT_VERSION_DATE TIMESTAMP ,
  IS_LAST_VERSION NUMBER(1,0),
  REPLACED_BY VARCHAR2(255),
  REPLACE_TO VARCHAR2(255),
  VERSION_RATIONALE_FK NUMBER(19),
  VERSION_RATIONALE_TYPE VARCHAR2(255),
  VR_CREATOR VARCHAR2(255),
  VR_CONTRIBUTOR VARCHAR2(255),
  VR_SUBMITTED VARCHAR2(255),
  VR_ACCEPTED VARCHAR2(255),
  VR_ISSUED VARCHAR2(255),
  VR_OUT_OF_PRINT VARCHAR2(255),
  CREATOR_FK NUMBER(19),
  PROC_STATUS VARCHAR2(255),
  TYPE VARCHAR2(255),
  FORMAT VARCHAR2(255)
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000) NOT NULL,
  LOCALE VARCHAR2(255) NOT NULL,
  IS_UNMODIFIABLE NUMBER(1,0),
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_DATASETS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_DATASETS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  STATISTICAL_RESOURCE_FK NUMBER(19) NOT NULL,
  DATASET_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_DATASOURCES (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  STATISTICAL_RESOURCE_FK NUMBER(19) NOT NULL,
  DATASET_VERSION_FK NUMBER(19)
);


CREATE TABLE TB_PUBLICATIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_PUBLICATIONS_VERSIONS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  STATISTICAL_RESOURCE_FK NUMBER(19) NOT NULL,
  PUBLICATION_FK NUMBER(19) NOT NULL
);


CREATE TABLE TB_QUERIES (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  STATISTICAL_RESOURCE_FK NUMBER(19) NOT NULL
);



-- Create many to many relations
    
CREATE TABLE TB_EI_CONTRIBUTORS (
  TB_EXTERNAL_ITEM_FK NUMBER(19) NOT NULL,
  TB_STATISITCAL_RESOURCES NUMBER(19) NOT NULL
);


CREATE TABLE TB_EI_MEDIATORS (
  TB_EXTERNAL_ITEM_FK NUMBER(19) NOT NULL,
  TB_STATISITCAL_RESOURCES NUMBER(19) NOT NULL
);


CREATE TABLE TB_EI_PUBLISHERS (
  TB_EXTERNAL_ITEM_FK NUMBER(19) NOT NULL,
  TB_STATISITCAL_RESOURCES NUMBER(19) NOT NULL
);



-- Primary keys
    
ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT PK_TB_STATISTICAL_RESOURCES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_DATASETS ADD CONSTRAINT PK_TB_DATASETS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_DATASETS_VERSIONS ADD CONSTRAINT PK_TB_DATASETS_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_DATASOURCES ADD CONSTRAINT PK_TB_DATASOURCES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_PUBLICATIONS ADD CONSTRAINT PK_TB_PUBLICATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_PUBLICATIONS_VERSIONS ADD CONSTRAINT PK_TB_PUBLICATIONS_VERSIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_QUERIES ADD CONSTRAINT PK_TB_QUERIES
	PRIMARY KEY (ID)
;

    
ALTER TABLE TB_EI_CONTRIBUTORS ADD CONSTRAINT PK_TB_EI_CONTRIBUTORS
	PRIMARY KEY (TB_EXTERNAL_ITEM_FK, TB_STATISITCAL_RESOURCES)
;

ALTER TABLE TB_EI_MEDIATORS ADD CONSTRAINT PK_TB_EI_MEDIATORS
	PRIMARY KEY (TB_EXTERNAL_ITEM_FK, TB_STATISITCAL_RESOURCES)
;

ALTER TABLE TB_EI_PUBLISHERS ADD CONSTRAINT PK_TB_EI_PUBLISHERS
	PRIMARY KEY (TB_EXTERNAL_ITEM_FK, TB_STATISITCAL_RESOURCES)
;


-- Unique constraints
    



ALTER TABLE TB_STATISTICAL_RESOURCES
    ADD CONSTRAINT UQ_TB_STATISTICAL_RESOURCES UNIQUE (UUID)
;




ALTER TABLE TB_DATASETS
    ADD CONSTRAINT UQ_TB_DATASETS UNIQUE (UUID)
;



ALTER TABLE TB_DATASETS_VERSIONS
    ADD CONSTRAINT UQ_TB_DATASETS_VERSIONS UNIQUE (UUID)
;



ALTER TABLE TB_DATASOURCES
    ADD CONSTRAINT UQ_TB_DATASOURCES UNIQUE (UUID)
;



ALTER TABLE TB_PUBLICATIONS
    ADD CONSTRAINT UQ_TB_PUBLICATIONS UNIQUE (UUID)
;



ALTER TABLE TB_PUBLICATIONS_VERSIONS
    ADD CONSTRAINT UQ_TB_PUBLICATIONS_VERSIONS UNIQUE (UUID)
;



ALTER TABLE TB_QUERIES
    ADD CONSTRAINT UQ_TB_QUERIES UNIQUE (UUID)
;



-- Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT FK_TB_STATISTICAL_RESOURCES_24
	FOREIGN KEY (OPERATION_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTE13
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID) ON DELETE CASCADE
;

  
  
  
ALTER TABLE TB_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_DATASETS_VERSIONS_STAT85
	FOREIGN KEY (STATISTICAL_RESOURCE_FK) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;
ALTER TABLE TB_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_DATASETS_VERSIONS_DATA05
	FOREIGN KEY (DATASET_FK) REFERENCES TB_DATASETS (ID) ON DELETE CASCADE
;

  
ALTER TABLE TB_DATASOURCES ADD CONSTRAINT FK_TB_DATASOURCES_STATISTICA52
	FOREIGN KEY (STATISTICAL_RESOURCE_FK) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;
ALTER TABLE TB_DATASOURCES ADD CONSTRAINT FK_TB_DATASOURCES_DATASET_VE01
	FOREIGN KEY (DATASET_VERSION_FK) REFERENCES TB_DATASETS_VERSIONS (ID) ON DELETE CASCADE
;

  
  
  
ALTER TABLE TB_PUBLICATIONS_VERSIONS ADD CONSTRAINT FK_TB_PUBLICATIONS_VERSIONS_83
	FOREIGN KEY (STATISTICAL_RESOURCE_FK) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;
ALTER TABLE TB_PUBLICATIONS_VERSIONS ADD CONSTRAINT FK_TB_PUBLICATIONS_VERSIONS_99
	FOREIGN KEY (PUBLICATION_FK) REFERENCES TB_PUBLICATIONS (ID) ON DELETE CASCADE
;

  
ALTER TABLE TB_QUERIES ADD CONSTRAINT FK_TB_QUERIES_STATISTICAL_RE28
	FOREIGN KEY (STATISTICAL_RESOURCE_FK) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;

  

ALTER TABLE TB_EI_CONTRIBUTORS ADD CONSTRAINT FK_TB_EI_CONTRIBUTORS_TB_EXT87
	FOREIGN KEY (TB_EXTERNAL_ITEM_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_EI_CONTRIBUTORS ADD CONSTRAINT FK_TB_EI_CONTRIBUTORS_TB_STA71
	FOREIGN KEY (TB_STATISITCAL_RESOURCES) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;

  
ALTER TABLE TB_EI_MEDIATORS ADD CONSTRAINT FK_TB_EI_MEDIATORS_TB_EXTERN83
	FOREIGN KEY (TB_EXTERNAL_ITEM_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_EI_MEDIATORS ADD CONSTRAINT FK_TB_EI_MEDIATORS_TB_STATIS71
	FOREIGN KEY (TB_STATISITCAL_RESOURCES) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;

  
ALTER TABLE TB_EI_PUBLISHERS ADD CONSTRAINT FK_TB_EI_PUBLISHERS_TB_EXTER20
	FOREIGN KEY (TB_EXTERNAL_ITEM_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_EI_PUBLISHERS ADD CONSTRAINT FK_TB_EI_PUBLISHERS_TB_STATI88
	FOREIGN KEY (TB_STATISITCAL_RESOURCES) REFERENCES TB_STATISTICAL_RESOURCES (ID)
;

  


-- Index
CREATE INDEX IX_TB_STATISTICAL_RESOURCES_68
    ON TB_STATISTICAL_RESOURCES (STATISTICAL_RESOURCE_TYPE ASC)
;


	