ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT URN_UNIQUE UNIQUE(URN);

-- Foreign keys
ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT FK_TB_STA_RES_TITLE FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);
ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT FK_TB_STA_RES_DESCRIPTION FOREIGN KEY (DESCRIPTION_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);
ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT FK_TB_STA_RES_VER_RATIONALE FOREIGN KEY (VERSION_RATIONALE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);

ALTER TABLE TB_STATISTICAL_RESOURCES ADD CONSTRAINT FK_TB_STA_RES_CREATOR FOREIGN KEY (CREATOR_FK) REFERENCES TB_EXTERNAL_ITEMS (ID);
