CREATE sequence SEQ_I18NSTRS;
CREATE sequence SEQ_L10NSTRS;
CREATE sequence SEQ_LOCALISED_STRINGS;

CREATE sequence SEQ_DATASOURCES;
CREATE sequence SEQ_QUERIES;

CREATE sequence SEQ_PUBLICATIONS_VERSIONS;
CREATE sequence SEQ_PUBLICATIONS;

CREATE sequence SEQ_DATASETS_VERSIONS;
CREATE sequence SEQ_DATASETS;

CREATE sequence SEQ_STATISTICAL_RESOURCES;

CREATE sequence SEQ_EXTERNAL_ITEMS;
CREATE sequence SEQ_INTERNATIONAL_STRINGS;