-- Eliminar campos de relaciones no necesarios o posiblemente calculables


drop table TB_RR_IS_PART_OF;

-- Recover data ?
drop table TB_RR_HAS_PART;


CREATE TABLE TB_RR_HAS_PART (
  HAS_PART_FK NUMBER(19) NOT NULL,
  PUB_VERSION_FK NUMBER(19) NOT NULL
);

ALTER TABLE TB_RR_HAS_PART ADD CONSTRAINT PK_TB_RR_HAS_PART
	PRIMARY KEY (HAS_PART_FK, PUB_VERSION_FK)
;

ALTER TABLE TB_RR_HAS_PART ADD CONSTRAINT FK_TB_RR_HAS_PART_HAS_PART_FK
	FOREIGN KEY (HAS_PART_FK) REFERENCES TB_RELATED_RESOURCES (ID) DEFERRABLE initially IMMEDIATE
;
ALTER TABLE TB_RR_HAS_PART ADD CONSTRAINT FK_TB_RR_HAS_PART_PUB_VERSIO01
	FOREIGN KEY (PUB_VERSION_FK) REFERENCES TB_PUBLICATIONS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE
;
