-- Cambiar el metadato COPYRIGHTED_DATE para que sólo almacene año
ALTER TABLE TB_STAT_RESOURCES DROP (COPYRIGHTED_DATE_TZ, COPYRIGHTED_DATE); 
ALTER TABLE TB_STAT_RESOURCES ADD COPYRIGHTED_DATE NUMBER(10);


-- Eliminar el campo URI puesto que es cumplimentado por la API
ALTER TABLE TB_STAT_RESOURCES DROP (URI); 