-- METAMAC-1910: Traducción de códigos temporales

1) Crear tabla de traducciones

	CREATE sequence SEQ_TRANSLATIONS;
	
	CREATE TABLE TB_TRANSLATIONS (
	  ID NUMBER(19) NOT NULL,
	  CODE VARCHAR2(255 CHAR) NOT NULL,
	  TITLE_FK NUMBER(19) NOT NULL
	);
	
	ALTER TABLE TB_TRANSLATIONS ADD CONSTRAINT PK_TB_TRANSLATIONS PRIMARY KEY (ID);
	ALTER TABLE TB_TRANSLATIONS ADD CONSTRAINT FK_TB_TRANSLATIONS_TITLE_FK FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID) DEFERRABLE initially IMMEDIATE;
	ALTER TABLE TB_TRANSLATIONS ADD CONSTRAINT CODE_UNIQUE UNIQUE(CODE) DEFERRABLE INITIALLY DEFERRED;


2) Ejecutar script '03-statistical-resources-inserts-translations.sql'